	-- Bench item
	['gunsmithgench']   = {['name']='gunsmithgench',   ['label']='Gunsmith Bench',   ['weight']=1000, ['type']='item', ['image']='gunsmithgench.png',   ['unique']=false, ['useable']=true,  ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Place a gunsmith workbench.'},

	-- Core materials
	['wood']            = {['name']='wood',            ['label']='Wood',             ['weight']=100,  ['type']='item', ['image']='wood.png',            ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Basic crafting material.'},
	['ironore']         = {['name']='ironore',         ['label']='Iron Ore',         ['weight']=100,  ['type']='item', ['image']='ironore.png',         ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Ore used for crafting.'},
	['iron_bar']        = {['name']='iron_bar',        ['label']='Iron Bar',         ['weight']=120,  ['type']='item', ['image']='iron_bar.png',        ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Refined iron bar.'},
	['steel']           = {['name']='steel',           ['label']='Steel',            ['weight']=120,  ['type']='item', ['image']='steel.png',           ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Refined steel.'},
	['coal']            = {['name']='coal',            ['label']='Coal',             ['weight']=80,   ['type']='item', ['image']='coal.png',            ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Fuel and gunpowder ingredient.'},
	['copperore']       = {['name']='copperore',       ['label']='Copper Ore',       ['weight']=100,  ['type']='item', ['image']='copperore.png',       ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Ore used for casings.'},
	['leadore']         = {['name']='leadore',         ['label']='Lead Ore',         ['weight']=100,  ['type']='item', ['image']='leadore.png',         ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Ammo material.'},
	['feathers']        = {['name']='feathers',        ['label']='Feathers',         ['weight']=10,   ['type']='item', ['image']='feathers.png',        ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Used for arrows.'},
	['twine']           = {['name']='twine',           ['label']='Twine',            ['weight']=10,   ['type']='item', ['image']='twine.png',           ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Binding material.'},
	['bolts']           = {['name']='bolts',           ['label']='Bolts',            ['weight']=50,   ['type']='item', ['image']='bolts.png',           ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Hardware parts.'},
	['morphine']        = {['name']='morphine',        ['label']='Morphine',         ['weight']=1,    ['type']='item', ['image']='morphine.png',        ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Toxic/medical component.'},
	['perfect_bear_pelt']= {['name']='perfect_bear_pelt',['label']='Perfect Bear Pelt',['weight']=500, ['type']='item', ['image']='perfect_bear_pelt.png',['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='High-quality pelt.'},
	['oilcan']          = {['name']='oilcan',          ['label']='Oil Can',          ['weight']=50,   ['type']='item', ['image']='oilcan.png',          ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Lubricant/oil supply.'},

	-- Intermediates
	['gunpowder']       = {['name']='gunpowder',       ['label']='Gunpowder',        ['weight']=50,   ['type']='item', ['image']='gunpowder.png',       ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Ammo ingredient.'},
	['shellcasing']     = {['name']='shellcasing',     ['label']='Shell Casing',     ['weight']=20,   ['type']='item', ['image']='shellcasing.png',     ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Ammo casing.'},
	['tnt']             = {['name']='tnt',             ['label']='TNT',              ['weight']=200,  ['type']='item', ['image']='tnt.png',             ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Explosive.'},

	-- Weapon components
	['frame']   = {['name']='frame',   ['label']='Frame',   ['weight']=100, ['type']='item', ['image']='frame.png',   ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Gun frame.'},
	['barrel']  = {['name']='barrel',  ['label']='Barrel',  ['weight']=120, ['type']='item', ['image']='barrel.png',  ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Gun barrel.'},
	['cylinder']= {['name']='cylinder',['label']='Cylinder',['weight']=80,  ['type']='item', ['image']='cylinder.png',['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Revolver cylinder.'},
	['trigger'] = {['name']='trigger', ['label']='Trigger', ['weight']=20,  ['type']='item', ['image']='trigger.png', ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Trigger mechanism.'},
	['grip']    = {['name']='grip',    ['label']='Grip',    ['weight']=40,  ['type']='item', ['image']='grip.png',    ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Gun grip.'},
	['stock']   = {['name']='stock',   ['label']='Stock',   ['weight']=100, ['type']='item', ['image']='stock.png',   ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Rifle stock.'},
	['sight']   = {['name']='sight',   ['label']='Sight',   ['weight']=20,  ['type']='item', ['image']='sight.png',   ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Gun sight.'},
	['bolt']    = {['name']='bolt',    ['label']='Bolt',    ['weight']=80,  ['type']='item', ['image']='bolt.png',    ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Bolt component.'},
	['action']  = {['name']='action',  ['label']='Action',  ['weight']=120, ['type']='item', ['image']='action.png',  ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Action group.'},
	['spring']  = {['name']='spring',  ['label']='Spring',  ['weight']=10,  ['type']='item', ['image']='spring.png',  ['unique']=false, ['useable']=false, ['shouldClose']=true, ['combinable']=nil, ['level']=0, ['description']='Spring component.'},
